### ISSUE TITLE
Experiencing with avatar won't work to use asl gesture

### ISSUE THREAD

**Issue by FurryDaniel** [I5UCC/VRC-ASL_Gestures#10]
I've tried download other avatars or free avatar then I added it and tested it is not working, I figured out

![image](https://github.com/I5UCC/VRC-ASL_Gestures/assets/55887183/002602a2-b2d0-4aa2-b973-032193e296d7)

Need to be deleted and it work but why using default avatar than gesture isn't work also my friends had problem with gesture not working cause for cached or saved is not changed with gesture.

I am sure everyone can see what I am doing and still working.

How did it work?
When you created an avatar and tested then add asl gesture to require delete aka in avatar OSC folder and the same is ID avatar then it is working now.

Could you make something if that's possible?

**Comment by I5UCC** [comment]
I'm reading this pretty late but ill still reply to it what i get from this issue. Yes the way that VRChat manages OSC Parameters is a little bit weird, it creates a configuration once, then it just keeps that osc configuration even tho the avatar has been updated with new Parameters it should incorporate. Sadly it doesnt. So we have to either add those new parameters to the config ourselves, or just delete that config so VRChat can create a new one. In the [ThumbparamsOSC repo](https://github.com/I5UCC/VRCThumbParamsOSC#osc-troubleshoot) there is a section for osc-troubleshoot, which basically just goes over that exact issue. the configuratior that comes with ThumbparamsOSC comes with a button that quickly clears that OSC config

**Comment by FurryDaniel** [comment]
Thank, I'll redownload for update it then I'll take look it the problem. Sometimes it like flicking when I sign them badly glitch.
