### ISSUE TITLE
Name Space does not exist 

### ISSUE THREAD

**Issue by AWulf1** [I5UCC/VRC-ASL_Gestures#2]
Added the V2.0 package to Unity and without adding anything and building for windows I got this issue. 

Working on Dakota https://payhip.com/b/isukj

![1](https://user-images.githubusercontent.com/17420676/173938044-3ca7b4b7-498b-4d63-9678-50fd3e06aede.png)
![2](https://user-images.githubusercontent.com/17420676/173938050-2280fd9e-e297-4e5a-bb7f-647f79614ffc.png)

**Comment by I5UCC** [comment]
Are you working with the latest SDK?

**Comment by AWulf1** [comment]
Hey I5UCC, Yes I'm using the creator Companion so it keeps the basic tools updated, It might be an issue with VRCAvatar3Tools. As that's the only addition I use. 
Thanks for letting me know I will continue to play with it and let you know when I get it working on a project.

**Comment by I5UCC** [comment]
Okay, thanks for the info, i havent looked at the creator companion. Ill take a look at it and see if it causes issues in any way.

**Comment by I5UCC** [comment]
Found the issue, i forgot to put the cs files into the Editor folder so they get ignored on upload, fixed on newest release. Thanks for pulling up this issue!

**Comment by AWulf1** [comment]
Yup I can confirm it does compile correctly and the avatar uploads now! :D
