### ISSUE TITLE
Support for ChilloutVR

### ISSUE THREAD

**Issue by Malachiel87** [I5UCC/VRC-ASL_Gestures#4]
Hi, i would be glad if this project will support also ChilloutVR ^^ https://documentation.abinteractive.net/chilloutvr/

Thank you <3

**Comment by I5UCC** [comment]
Currently working on it, a repository already exists for it too! https://github.com/I5UCC/CVR-ASL_Gestures

Though ChilloutVR still has some limitations that hold me back a bit. Its CCK (Content Creation Kit) currently lacks an alternative of VRC's "Animator Tracking Control" component for animation states which are very important for Index. Hopefully i will find a solution or workaround for those limitations. I will send a feature request to CVR to allow tracking control on the fly, or we somehow develop a mod for the game that solves this problem (at least that is plausible, thank you *not* VRC)

So far I can only support GeneralVR/Meta but not Index, this will be available somewhat soon. 

I will hold those projects seperate as I dont wanna mix anything.

Thanks for creating this issue!

**Comment by Malachiel87** [comment]
Glad to hear that, maybe if some feature that CVR is missing will come out with next api (you can also reach to discord and ask more info if you want https://discord.gg/ABI
